Ignore ws crashes
graphile/postgraphile pull request #1550
Opened 2021-10-28 16:53 UTC by purge

- catch ws errors and ignore them
- allow handler to be overridden

## Description

## Performance impact

## Security impact

## Checklist

- [ ] My code matches the project's code style and `yarn lint:fix` passes.
- [ ] I've added tests for the new feature, and `yarn test` passes.
- [ ] I have detailed the new feature in the relevant documentation.
- [ ] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).
- [ ] If this is a breaking change I've explained why.

2021-11-24 14:58 UTC, benjie requested changes
This looks good; are there situations in which we need to do cleanup in the 'error' handler though? Maybe @enisdenjo would know?

Interestingly neither the `ws` docs nor the `graphql-ws` docs seem to show examples adding error handlers...

2021-11-24 14:58 UTC, benjie commented on src/postgraphile/http/subscriptions.ts
> +                'the following error thrown from `ws` was caught and ignored. if you want to handle it yourself pass an onError handler',
```suggestion
                'The following error thrown from `ws` was caught and ignored.',
```

2021-11-24 14:59 UTC, benjie approved these changes

2021-11-24 16:22 UTC, enisdenjo commented
Actually, [`graphql-ws@v5.5.4`](https://github.com/enisdenjo/graphql-ws/releases/tag/v5.5.4) started [doing something similar](https://github.com/enisdenjo/graphql-ws/commit/a22c00ff406f19ca706afdf6fdd7de98571bce78). Updating to the latest version, this PR might want to reconsider the then [extraneous `console.log`](https://github.com/purge/postgraphile/blob/eddfb126b48890b04ffb62a458497d5f3da1a809/src/postgraphile/http/subscriptions.ts#L491-L494) because [`useServer` leaves logs too](https://github.com/enisdenjo/graphql-ws/blob/239dafeb65d0cf057962f73e5ba7d6f2bd00c82d/src/use/ws.ts#L55-L95).

Furthermore, `graphql-ws` itself has no error handling examples because the lib logs to the console now too, and because all errors emitted on the WebSocket server (or its sockets) are considered fatal to the connection(s) anyways. After observing the error, there's nothing you can do to keep the connection alive. With this in mind, I just decided to not bother and keep the docs lean. But, maybe I should bother? 🤔

2021-11-24 18:54 UTC, benjie commented
@enisdenjo A paragraph about it might help :) "Since graphql-ws@x.y.z it's no longer necessary to add 'event' handlers to ws connections as we handle this internally because ..."

So what you're saying @enisdenjo is we should just upgrade to the latest version.

@purge since graphql-ws has a `^` range, does upgrading graphql-ws address your issue without these changes being required?

2021-11-25 10:54 UTC, purge commented
Yep, upgrading to `graphql-ws >= 5.5.4` no longer crashes the server. i'll re-raise as an updated minimum dep

2021-11-25 10:54 UTC, closed without merging